# inference-perf/values.yaml
job:
  image:
    repository: quay.io/inference-perf/inference-perf
    tag: "latest" # Defaults to .Chart.AppVersion
  nodeSelector: {}
  serviceAccountName: "workload-identity-k8s-sa"
  # Example resources:
  # resources:
  #   requests:
  #     cpu: "1"
  #     memory: "4Gi"
  #   limits:
  #     cpu: "2"
  #     memory: "8Gi"
  resources: {}

logLevel: INFO

# A GCS bucket path that points to the dataset file.
# The file will be copied from this path to the local file system
# at /gcsDataset/gcs-dataset.json for use during the run.
# NOTE: For this dataset to be used, config.data.path must also be explicitly set to /gcsDataset/gcs-dataset.json.
# Format: bucket-name/folder/to/dataset/file
gcsPath: ""

# An S3 bucket path that points to the dataset file.
# The file will be copied from this path to the local file system
# at /s3Dataset/s3-dataset.json for use during the run.
# NOTE: For this dataset to be used, config.data.path must also be explicitly set to /s3Dataset/s3-dataset.json.
# Format: bucket-name/folder/to/dataset/file
s3Path: ""

# Optional Token configuration for Hugging Face authentication.
# hfSecret: Configures a pre-existing Kubernetes Secret.
# hfToken: Creates a new kubernetes secret with the specified token.
# If both specified, 'hfSecret' takes precedence over 'hfToken'.
token:
  hfSecret:
    name: "" # The name of the existing Secret (e.g., 'my-hf-secret').
    key: ""  # The key within the Secret that holds the token value (e.g., 'token' or 'hf-token').
  hfToken: ""

config:
  load:
    request_timeout: 600
    worker_max_concurrency: 250
    worker_max_tcp_connections: 750
    type: constant
    interval: 60.0
    stages:
      - rate: 5
        duration: 60
      - rate: 10
        duration: 60
      - rate: 15
        duration: 60
      - rate: 20
        duration: 60
      - rate: 25
        duration: 60
      - rate: 30
        duration: 60
      - rate: 35
        duration: 60
      - rate: 40
        duration: 60
  api:
    type: chat
    streaming: true
  server:
    type: vllm
    model_name: Qwen/Qwen3-VL-32B-Instruct
    ignore_eos: true
  tokenizer:
    pretrained_model_name_or_path: Qwen/Qwen3-VL-32B-Instruct
  data:
    type: synthetic
    input_distribution:
      min: 10
      max: 100
      mean: 50
      std_dev: 50
      total_count: 10800
    output_distribution:
      min: 100
      max: 300
      mean: 200
      std_dev: 50
      total_count: 10800
    multimodal:
      image:
       count: { type: uniform, min: 1, max: 3, mean: 2 }
       insertion_point: 1.0
       resolutions:
         - resolution: "720p"
           weight: 1
  report:
    request_lifecycle:
      summary: true
      per_stage: true
      per_request: false
